services:

  nre_ai:

    build: .
    container_name: nre
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8000:8000"
      - "9000:9000"
    working_dir: /app
    # need to be changed to named volume like postgres
    # on produciton level only
    volumes:
      - ./src/:/app/src
      - ./scripts:/app/scripts
      - ./tests/:/app/tests
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock

    environment:
      UV_LINK_MODE: copy
      PATH: "/app/.venv/bin:$PATH"
    networks:
      - app-network

  db:

    image: postgres:17.2
    container_name: nre_db
    restart: always
    environment:
      POSTGRES_USER: vronst
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nre_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

# TODO: maybe some healthchecks?

networks:
  app-network:
    driver: bridge

# named volumes
volumes:
  postgres_data:

