# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python regressions tests and draft pull request

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        if [ -f requirements.txt ]; then uv add -r requirements.txt; fi
        uv sync --frozen

    - name: Regression tests with pytest
      run: |
        uv run pytest -m regression
    - name: Create Draft Pull Request to Stage
      if: success()
      uses: peter-evans/create-pull-request@v7
      with:
          base: stage
          token: ${{ secrets.PRO_TOKEN }}
          commit-message: "Automated regression test results"
          branch: regression-results
          branch-suffix: timestamp
          title: "Automated Regression Test Results"
          body: |
            This pull request contains the results of the latest regression tests.
          signoff: true
          delete-branch: true
          draft: true
